### PR TITLE
Revert change that caused some failing jobs to restart indefinitely.

### PR DESCRIPTION
**Pull request by ClintAtTheBroad**
Always transition jobs to `Running` state when they're submitted to a DRM system; this fixes a bug introduced in a previous PR where jobs were transitioned to `Submitted` on submission instead, resulting in short-lived failing jobs restarting forever, if they never entered the `Running` state and had their run counts incremented.

PS: The integration tests passed.

### CODE REVIEW

**Comment by massung** [comment]
Code looks fine, just wanted to ask if you feel that this is more of a hack fix? 

The `Submitted` state doesn't appear to be removed, but is it used any more? If so, what for since the jobs all transition to `Running` immediately instead? If it's used for another purpose (e.g. being submitted) then perhaps renaming it to something more active like `Submitting` would make more sense?

**Comment by ClintAtTheBroad** [comment]
> Code looks fine, just wanted to ask if you feel that this is more of a hack fix?

I'm not sure how to answer that.

> The Submitted state doesn't appear to be removed, but is it used any more?

It is.  Jobs are transitioned through states explicitly by LS code (as here) and by (in the case of DRM jobs) responding to job status changes indicated by remote systems (Uger and LSF).  LS doesn't explicitly set any statuses to `Submitted` anymore, but that's still a valid state that LS might assign in response to information from Uger or LSF, say if they put a job into any one of 4+ states that basically mean "queued and not yet running".

> then perhaps renaming it to something more active like Submitting would make more sense?

At the point in the code we're talking about, the jobs are already submitted; there's no active submitting going on.  

That jobs are marked 'Running' (from the LS perspective) when they might be queued or otherwise not yet running from the Uger/LSF perspective is an issue, but one that's been minor in practice so far.  How job states are transitioned and run counts are updated in general is in need of an overhaul, but that's beyond the scope of this PR.  I meant for this to be the simplest thing that could work.

**Comment by massung** [comment]
> > Code looks fine, just wanted to ask if you feel that this is more of a hack fix?

> I'm not sure how to answer that.

Maybe the question came across wrong. Without knowing the intricacies, my brain started down the following path:

* Is `Submitted` still needed (hence follow-up questions)?
* Are the jobs _actually_ running (or pending or something else)?
* If not _actually_ running, then does it make sense for them to be in that state? Could that lead a user or fellow programmer to make assumptions (during debugging) that aren't true?
* Is it different code that needs to be "fixed" to understand `Submitted` instead of just bashing the state to `Running` (and that led me to the word "hack" to indicate a simple, quick fix that gets things going again, but may not quite be the best long-term solution to the issue)?

I'm not trying to imply that these questions are pointing at a better solution; I have no idea. Based on your other answers, it seems like LS considers a job as `Running` as soon as it was sent off to the DRM even if it might actually be waiting to run, etc. That's cool.

Hope that makes sense. ;)

**Comment by massung** [comment]
Still, the code seems fine. As long as my follow-up questions are unnecessary to address (most likely), just let me know and I'll merge.

**Comment by ClintAtTheBroad** [comment]
> and that led me to the word "hack" to indicate a simple, quick fix that gets things going again, but may not quite be the best long-term solution to the issue

In that sense, then yes, this was a hack.  The code in question needs an overhaul, including, but not limited to - some rules (a state machine?) for what states a job can transition to from which other states; consolidating the job-lifecycle tracking and management code; and consolidating the code related to restarting jobs.  All that stuff should happen (if it ever does) in another PR.  This one was to get Ryan going when he was stuck. 

> As long as my follow-up questions are unnecessary to address (most likely), just let me know and I'll merge.

I think they are, at least in this PR.

**Pull request merged**
